-- Smart Melon backend, initial schema.
--
-- Two ideas drive this schema and are worth stating before anyone extends it:
--
--   1. Hardware is data, not schema. There is no pH column, no NPK table and no pump table. A new
--      sensor or actuator is a row in `sensor` / `actuator`, so the hardware team can change the
--      instrument set without a migration and without touching business code.
--
--   2. Telemetry is stored twice, on purpose. `telemetry_message` keeps the raw payload exactly as
--      it arrived (jsonb) so a message can be inspected or replayed while the payload contract is
--      still moving; `sensor_reading` keeps the same values normalised so history queries stay
--      cheap and indexable.
--
-- Status and severity values are stored as text rather than enum types or CHECK constraints. An
-- edge device or a later phase must be able to introduce a value this build has never heard of
-- without a schema change; the application layer owns the vocabulary.

-- ---------------------------------------------------------------------------
-- Accounts
-- ---------------------------------------------------------------------------
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(128),
    role          VARCHAR(32)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

COMMENT ON COLUMN app_user.password_hash IS 'BCrypt hash. The plain password is never stored or logged.';

-- ---------------------------------------------------------------------------
-- Devices
-- ---------------------------------------------------------------------------
CREATE TABLE device (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_code  VARCHAR(64)  NOT NULL,
    name         VARCHAR(128) NOT NULL,
    type         VARCHAR(64),
    status       VARCHAR(16)  NOT NULL DEFAULT 'UNKNOWN',
    last_seen_at TIMESTAMPTZ,
    description  VARCHAR(255),
    metadata     JSONB,
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_device_code UNIQUE (device_code)
);

COMMENT ON COLUMN device.device_code IS 'Business identifier; also the {deviceId} segment of this device MQTT topics.';
COMMENT ON COLUMN device.status IS 'ONLINE / OFFLINE / UNKNOWN. Derived from last_seen_at and the configured timeout.';

CREATE INDEX idx_device_status ON device (status);

-- ---------------------------------------------------------------------------
-- Sensors
-- ---------------------------------------------------------------------------
CREATE TABLE sensor (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       BIGINT       NOT NULL,
    code            VARCHAR(64)  NOT NULL,
    metric_key      VARCHAR(64)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    type            VARCHAR(64),
    unit            VARCHAR(32),
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    auto_registered BOOLEAN      NOT NULL DEFAULT FALSE,
    description     VARCHAR(255),
    metadata        JSONB,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_sensor_device FOREIGN KEY (device_id) REFERENCES device (id),
    CONSTRAINT uk_sensor_device_code UNIQUE (device_id, code),
    CONSTRAINT uk_sensor_device_metric UNIQUE (device_id, metric_key)
);

COMMENT ON COLUMN sensor.metric_key IS 'Key this sensor uses inside a telemetry payload, e.g. "temperature".';
COMMENT ON COLUMN sensor.auto_registered IS 'Created from an unrecognised telemetry metric; starts disabled pending operator review.';

-- ---------------------------------------------------------------------------
-- Actuators
-- ---------------------------------------------------------------------------
CREATE TABLE actuator (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id        BIGINT       NOT NULL,
    code             VARCHAR(64)  NOT NULL,
    name             VARCHAR(128) NOT NULL,
    type             VARCHAR(64),
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    current_state    VARCHAR(32),
    state_updated_at TIMESTAMPTZ,
    description      VARCHAR(255),
    metadata         JSONB,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_actuator_device FOREIGN KEY (device_id) REFERENCES device (id),
    CONSTRAINT uk_actuator_device_code UNIQUE (device_id, code)
);

COMMENT ON COLUMN actuator.current_state IS 'Last state REPORTED by the device. Never inferred from a command that was sent.';

-- ---------------------------------------------------------------------------
-- Telemetry: raw envelope plus normalised readings
-- ---------------------------------------------------------------------------
CREATE TABLE telemetry_message (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id     BIGINT,
    device_code   VARCHAR(64) NOT NULL,
    payload       JSONB       NOT NULL,
    source        VARCHAR(16) NOT NULL,
    status        VARCHAR(24) NOT NULL,
    error_message VARCHAR(512),
    recorded_at   TIMESTAMPTZ NOT NULL,
    received_at   TIMESTAMPTZ NOT NULL,
    metric_count  INTEGER     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_telemetry_device FOREIGN KEY (device_id) REFERENCES device (id)
);

COMMENT ON TABLE telemetry_message IS 'Raw inbound payloads, including rejected ones - the message that failed is the one someone needs to read.';
COMMENT ON COLUMN telemetry_message.device_id IS 'Null when the payload referenced a device that is not registered.';
COMMENT ON COLUMN telemetry_message.recorded_at IS 'Device-supplied timestamp, or the receive time when the device supplied none.';

CREATE INDEX idx_telemetry_device_received ON telemetry_message (device_id, received_at DESC);
CREATE INDEX idx_telemetry_status_received ON telemetry_message (status, received_at DESC);

CREATE TABLE sensor_reading (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telemetry_message_id BIGINT      NOT NULL,
    sensor_id            BIGINT      NOT NULL,
    device_id            BIGINT      NOT NULL,
    metric_key           VARCHAR(64) NOT NULL,
    numeric_value        NUMERIC(18, 6),
    text_value           VARCHAR(255),
    unit                 VARCHAR(32),
    recorded_at          TIMESTAMPTZ NOT NULL,
    received_at          TIMESTAMPTZ NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_reading_message FOREIGN KEY (telemetry_message_id) REFERENCES telemetry_message (id),
    CONSTRAINT fk_reading_sensor FOREIGN KEY (sensor_id) REFERENCES sensor (id),
    CONSTRAINT fk_reading_device FOREIGN KEY (device_id) REFERENCES device (id)
);

COMMENT ON COLUMN sensor_reading.numeric_value IS 'Numeric metrics live here so history can be aggregated and indexed.';
COMMENT ON COLUMN sensor_reading.text_value IS 'Non-numeric metrics (a state, a quality flag) without needing a schema change.';

CREATE INDEX idx_reading_sensor_recorded ON sensor_reading (sensor_id, recorded_at DESC);
CREATE INDEX idx_reading_device_recorded ON sensor_reading (device_id, recorded_at DESC);
CREATE INDEX idx_reading_message ON sensor_reading (telemetry_message_id);

-- ---------------------------------------------------------------------------
-- Actuator command history
-- ---------------------------------------------------------------------------
CREATE TABLE actuator_command (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_uid   VARCHAR(36) NOT NULL,
    actuator_id   BIGINT      NOT NULL,
    device_id     BIGINT      NOT NULL,
    command_type  VARCHAR(64) NOT NULL,
    parameters    JSONB,
    source        VARCHAR(16) NOT NULL,
    requested_by  BIGINT,
    status        VARCHAR(16) NOT NULL,
    requested_at  TIMESTAMPTZ NOT NULL,
    sent_at       TIMESTAMPTZ,
    executed_at   TIMESTAMPTZ,
    error_message VARCHAR(512),
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_command_uid UNIQUE (command_uid),
    CONSTRAINT fk_command_actuator FOREIGN KEY (actuator_id) REFERENCES actuator (id),
    CONSTRAINT fk_command_device FOREIGN KEY (device_id) REFERENCES device (id),
    CONSTRAINT fk_command_user FOREIGN KEY (requested_by) REFERENCES app_user (id)
);

COMMENT ON TABLE actuator_command IS 'Append-only audit: who commanded what, when, manually or automatically, and whether it worked.';
COMMENT ON COLUMN actuator_command.command_uid IS 'Correlation id put on the wire; the device echoes it in its acknowledgement.';
COMMENT ON COLUMN actuator_command.requested_by IS 'Null for AUTOMATION and SYSTEM commands.';
COMMENT ON COLUMN actuator_command.status IS 'PENDING / SENT / EXECUTED / FAILED / CANCELLED. SENT means the broker accepted it, not that hardware acted.';

CREATE INDEX idx_command_actuator_requested ON actuator_command (actuator_id, requested_at DESC);
CREATE INDEX idx_command_status_requested ON actuator_command (status, requested_at DESC);

-- ---------------------------------------------------------------------------
-- Plants (deliberately minimal; per-plant tracking is not a settled requirement)
-- ---------------------------------------------------------------------------
CREATE TABLE plant (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL,
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_plant_code UNIQUE (code)
);

-- ---------------------------------------------------------------------------
-- AI detections
-- ---------------------------------------------------------------------------
CREATE TABLE ai_detection (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id      BIGINT       NOT NULL,
    plant_id       BIGINT,
    detection_type VARCHAR(64)  NOT NULL,
    label          VARCHAR(128) NOT NULL,
    confidence     NUMERIC(5, 4),
    image_url      VARCHAR(512),
    metadata       JSONB,
    detected_at    TIMESTAMPTZ  NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_detection_device FOREIGN KEY (device_id) REFERENCES device (id),
    CONSTRAINT fk_detection_plant FOREIGN KEY (plant_id) REFERENCES plant (id)
);

COMMENT ON COLUMN ai_detection.label IS 'Class reported by the model. The backend stores it without interpreting it.';
COMMENT ON COLUMN ai_detection.plant_id IS 'Nullable: whether cultivation is tracked per plant is still an open question.';

CREATE INDEX idx_detection_detected ON ai_detection (detected_at DESC);
CREATE INDEX idx_detection_device_detected ON ai_detection (device_id, detected_at DESC);

-- ---------------------------------------------------------------------------
-- Alerts
-- ---------------------------------------------------------------------------
CREATE TABLE alert (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                VARCHAR(64)   NOT NULL,
    severity            VARCHAR(16)   NOT NULL,
    title               VARCHAR(160)  NOT NULL,
    message             VARCHAR(1000) NOT NULL,
    source              VARCHAR(16)   NOT NULL,
    related_device_id   BIGINT,
    related_sensor_id   BIGINT,
    related_actuator_id BIGINT,
    metadata            JSONB,
    acknowledged        BOOLEAN       NOT NULL DEFAULT FALSE,
    acknowledged_by     BIGINT,
    acknowledged_at     TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL,
    CONSTRAINT fk_alert_device FOREIGN KEY (related_device_id) REFERENCES device (id),
    CONSTRAINT fk_alert_sensor FOREIGN KEY (related_sensor_id) REFERENCES sensor (id),
    CONSTRAINT fk_alert_actuator FOREIGN KEY (related_actuator_id) REFERENCES actuator (id),
    CONSTRAINT fk_alert_ack_user FOREIGN KEY (acknowledged_by) REFERENCES app_user (id)
);

COMMENT ON TABLE alert IS 'Infrastructure alerts only in phase 1. Agronomic thresholds are not decided and none are hard-coded.';

CREATE INDEX idx_alert_ack_created ON alert (acknowledged, created_at DESC);
CREATE INDEX idx_alert_open_device ON alert (type, related_device_id) WHERE acknowledged = FALSE;

-- ---------------------------------------------------------------------------
-- Automation rules (table only; nothing evaluates them yet)
-- ---------------------------------------------------------------------------
CREATE TABLE automation_rule (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(128) NOT NULL,
    description          VARCHAR(255),
    enabled              BOOLEAN      NOT NULL DEFAULT FALSE,
    condition_expression JSONB,
    action_expression    JSONB,
    priority             INTEGER      NOT NULL DEFAULT 100,
    created_at           TIMESTAMPTZ  NOT NULL,
    updated_at           TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_automation_rule_name UNIQUE (name)
);

COMMENT ON TABLE automation_rule IS
    'Storage for phase 2. No rule is evaluated in this phase: automatic control of a pump or valve is a safety decision that waits for final hardware, sensor and threshold specifications.';
COMMENT ON COLUMN automation_rule.condition_expression IS 'Opaque JSON; the grammar is undecided and must not be guessed at here.';
